### ISSUE TITLE
TODO List: Soft launch of CEE 0.1.0

### ISSUE THREAD

**Issue by joeyklee** [ubccalp/docs#1]
# TODOs for the CEE 0.1.0

## TBD

- [ ] Remove CEE beta from Stormweb hosting // keep stormweb for domain name handling // reached out to Stormweb support on 20180406

## Completed
- [x] remove config data from the CEE beta config.php for security // details unused anyways
- [X] Add entire team to CALP Org ==> pending everyone sends their IDs and accepts the invite.
- [x] documentation for how to run everything locally & on server
- [X] Create Github Organization for CALP
- [X] Create tileserver repo in CALP Github Organization // see: https://github.com/ubccalp/tileserver
- [X] Create CEE beta in CALP Github Organization // see: https://github.com/ubccalp/energy-explorer-beta
- [X] add CEE beta to domain: `beta.energyexplorer.ca`
- [X] add `tiles.energyexplorer.ca` for tileserver domain
- [X] Deploy CEE beta to heroku & transfer ownership to Deepti's account // maintain as collaborator
- [X] Deploy tileserver to Digital Ocean
- [x] transfer tileserver to CALP digitalOcean account
- [X] add license CC BY-NC to repos
- [X] transfer ownership of calp-energy-explorer heroku instance to Deepti
- [X] Create CEE Latest to CALP Github Organization
- [X]  (things seem to be working) get data for Rory's household energy maps // I believe they were hosted on RedHat using tilehut.js but since that service has been deprecated, that data will no longer be available. // or it is on carto. need to check

**Comment by joeyklee** [comment]
will add last remaining issue as its own post
